version: '3.8'

services:
  mysql:
    image: juanjk24/arrive-on-time-db # usa la imagen de db de dockerhub
    container_name: mysql
    restart: always 
    env_file:
      - ./db/.env # archivo de variables de entorno para la base de datos
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql  

  backend:
    image: juanjk24/arrive-on-time-backend # usa la imagen del backend de dockerhub
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mysql

  frontend:
    image: juanjk24/arrive-on-time-frontend # usa la imagen del frontend de dockerhub
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql-data:
